apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: resource-server-claim0
  name: resource-server-claim0
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
