# This is for the dev, which means, root path is here
# Build Stage
FROM golang:1.25-alphine AS builder

WORKDIR /app

COPY ../go.mod ../go.sum ./
RUN go mod download

COPY ../ .

RUN CGO_ENABLE=0 GOOS=linux go build -p 1 -o main ./main

# Run Stage
FROM alphine:latest

WORKDIR /app

COPY --from=builder /app/main .

CMD ["./main"]